### ISSUE TITLE
MFunctor instance for EitherT

### ISSUE THREAD

**Issue by co-dan** [Gabriel439/Haskell-MMorph-Library#15]
Is it possible to include an `MFunctor` instance for the `EitherT` monad somehow?
I figured that the sensible implementation looks something like this:

``` haskell
instance MFunctor (EitherT l) where
  hoist nat m = EitherT (nat (runEitherT m))
```

**Comment by turion** [comment]
I think this has been addressed long since. Feel free to reopen if I'm mistaken.
