### ISSUE TITLE
Module ‘Control.Monad.Trans.Error’ is deprecated

### ISSUE THREAD

**Issue by andreasabel** [Gabriel439/Haskell-MMorph-Library#17]
Probably you are aware of this already, but for me it stops me from using your library (and other libraries that depend on yours).

```
[1 of 2] Compiling Control.Monad.Morph ( src/Control/Monad/Morph.hs, dist/build/Control/Monad/Morph.o )

src/Control/Monad/Morph.hs:76:1: Warning:
    Module ‘Control.Monad.Trans.Error’ is deprecated:
      Use Control.Monad.Trans.Except instead

src/Control/Monad/Morph.hs:116:20: Warning:
    In the use of type constructor or class ‘E.ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
```

**Comment by Gabriel439** [comment]
Could you submit a pull request to delete all `ErrorT`-related instances?

**Comment by bergmark** [comment]
Why does this stop you from using it?

I would recommend to keep these instances for anyone who is still using ErrorT.

**Comment by Gabriel439** [comment]
They will have to either be deleted or guarded with `#ifdef` statements eventually when `transformers` deletes `ErrorT`, but I can hold onto them for now.

**Comment by turion** [comment]
> I would recommend to keep these instances for anyone who is still using ErrorT.

They throw warnings and thus make the dependency `mmorph` a nuisance when compiling with `-Werror`.
