### ISSUE TITLE
Add a type for natural transformations

### ISSUE THREAD

**Issue by np** [Gabriel439/Haskell-MMorph-Library#27]
The servant-server package is defining a data type to hold a natural transformation (https://hackage.haskell.org/package/servant-server-0.4.4.6/docs/Servant-Server-Internal-Enter.html).

I claim that such a type needs a more appropriate home.

I was wondering if mmorph could be a good place.

**Comment by fizruk** [comment]
@np have you seen [`natural-transformation`](https://hackage.haskell.org/package/natural-transformation)?

**Comment by Gabriel439** [comment]
Yeah, I think `natural-transformation` is a natural home for this and I believe the `(:~>)` type from that package does what you want
