### ISSUE TITLE
Strengthen `hoist` constraints

### ISSUE THREAD

**Issue by khwarizmii** [Gabriel439/Haskell-MMorph-Library#38]
Hi! My company is using `mmorph` in our codebase. We would like to give an instance of `MFunctor` for the [_continuation passing style_ `WriterT`](https://github.com/minad/writer-cps-transformers/blob/master/src/Control/Monad/Trans/Writer/CPS/Internal.hs#L77) from `writer-cps-transformers`.  Sadly, we cannot do this correctly unless we strengthen the constraints on `hoist` like so:

```
hoist :: (Monad m, Monad n) => (forall a. m a -> n a) -> t m b -> t n b
```

Here's why: if you look at the CPS `WriterT`, it is superficially the same as `StateT`:

```
newtype WriterT w m a = WriterT (w -> m (a, w))
```

However, it has different semantics.  For one, `runWriterT` for this transformer is defined as follows:

```
runWriterT :: Monoid w => WriterT w m a -> m a
runWriterT (WriterT f) = f empty 
```

CPS `WriterT` also comes with a smart constructor so it can hide its internal state:

```
writerT :: (Functor f, Monoid w) => f (a, w) -> WriterT w f a
writerT f = WriterT $ \ w -> (\ (a, w') -> (a, w <> w')) <$> f
```

These two are inverses and obey the following laws. This distinguishes CPS `WriterT` from `StateT`:

```
runWriterT . writerT = id
writerT . runWriterT = id
```

We can't give the usual instance of `MFunctor` for CPS `WriterT` because of the `Functor` constraint unless we strengthen `hoist`:

```
-- Doesn't compile!
instance MFunctor (WriterT w) where
  hoist nat m = writerT (nat (runWriterT m))
```

I suspect that introducing a constraint on the second type constructor to be a monad might break some unlawful code. Otherwise I can't see how this change could introduce any backward incompatibility.

**Comment by Gabriel439** [comment]
@khwarizmii: Do you need to use `writerT`/`runWriterT` to implement the instance?  Could you implement it instead as:

```haskell
instance MFunctor (WriterT w) where
    hoist nat (WriterT f) = WriterT (\w -> nat (f w))
```

**Comment by khwarizmii** [comment]
Okay, this example is not exactly concrete. 

Let `unWriterT (WriterT f) = f`.  If the `StateT`-based instance for CPS `WriterT` were lawful it would demand the following equation be obeyed:

```
WriterT . nat . unWriterT $ (WriterT f) = writerT . nat . runWriterT $ WriterT f
```

Simplifying the LHS yields:

```
WriterT . nat . unWriterT $ (WriterT f) = WriterT . nat . f                          (1)
```

Expanding the RHS yields:

```
writerT . nat . runWriterT $ WriterT f
  = writerT . nat $ f empty
  = WriterT $ \ w -> (\ (a, w') -> (a, w <> w')) <$> nat (f empty)                   (2)
```

From (1) and (2) we have, for all natural transformations `nat`,

```
nat . f = \ w -> (\ (a, w') -> (a, w <> w')) <$> nat (f empty)
```

This doesn't appear to be obvious, although coming up with a counter example hasn't been fruitful for me.

**Comment by Gabriel439** [comment]
@khwarizmii: I can complete your proof.  The missing piece is that `nat` is a monad morphism and all monad morphisms are natural transformations, which must obey the following law:

```haskell
nat . fmap k = fmap k . nat
```

That means that you can rearrange this:

```haskell
nat . f = \ w -> (\ (a, w') -> (a, w <> w')) <$> nat (f empty)
```

... to this:

```haskell
nat . f = \ w -> nat ((\ (a, w') -> (a, w <> w')) <$> f empty)
```

... which you can further rearrange to:

```haskell
nat . f = nat . (\w -> (\ (a, w') -> (a, w <> w')) <$> f empty)
```

... which is true if:

```haskell
f = \w -> (\ (a, w') -> (a, w <> w')) <$> f empty
```

If we wrap both sides of that in the `WriterT` constructor

```haskell
WriterT f = WriterT (\w -> (\ (a, w') -> (a, w <> w')) <$> f empty)
```

... then we can recognize that the right-hand-side of that is the same as:

```haskell
WriterT f = (writerT . runWriterT) (WriterT f)
```

... and since `writerT . runWriterT = id` then we complete the proof:

```haskell
WriterT f = WriterT f
```

**Comment by khwarizmii** [comment]
Thanks!  I regret having to resort to skipping the smart contructor to write this instance, but presumably introducing the proposed monad constraint could be breaking to anyone abusing this library.

Thanks a lot for helping me work through the proof!

**Comment by Gabriel439** [comment]
@khwarizmii: You're welcome! 🙂
