### ISSUE TITLE
Module Control.Monad.Trans.List is deprecated

### ISSUE THREAD

**Issue by istathar** [Gabriel439/Haskell-MMorph-Library#49]
Another deprecation for you to consider.

    /tmp/stack6/mmorph-1.1.3/src/Control/Monad/Morph.hs:83:1: warning: [-Wdeprecations]
    Module `Control.Monad.Trans.List' is deprecated:
       This transformer is invalid on most monads
        |
     83 | import qualified Control.Monad.Trans.List          as L
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This was from GHC 8.6.5 compiling against Stackage snapshot `lts-14.6`.

AfC

**Comment by turion** [comment]
Replace it with https://hackage.haskell.org/package/list-t? Or https://hackage.haskell.org/package/pipes?

**Comment by turion** [comment]
Given that `list-t` and `pipes` have a dependency on `mmorph` already, probably the instance should be deleted.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/Gabriel439/Haskell-MMorph-Library/pull/63
